using '../main.bicep'

param workloadPrefix = 'cmhfuncs'
param workloadName = 'order'
param environmentName = 'dev'
param location = 'eastus2'
param serviceBusSku = 'Standard'
param maxTopicSize = 2048
param ordersTopicName = 'received-orders'
param ordersTopicSubscriptionName = 'auto-approved-orders'
param ordersForApprovalSubscriptionName = 'orders-requiring-approval'
param ordersTopicSqlFilter = 'user.orderTotal <= 1000'
param ordersForApprovalSqlFilter = 'user.orderTotal >= 1000'
param fulfillmentTopicName = 'orders-for-fulfillment'
param keyVaultAdminIdentities = ['2ede4c0c-360b-47f8-80b0-bdba8badea7b']
param cosmosDbDatabaseName = 'order-processing'
param ordersCosmosContainerName = 'orders'
param orderContainerPartitionKey = '/customerId'
param fulfillmentTopicSubscriptionName = 'all-approved-orders'
param shipmentTopicName = 'ready-for-shipment'
param shipmentTopicSubscriptionName = 'all-orders-for-shipment'
param cosmosLeaseContainerName = 'leases'
param statusNotificationTopicName = 'status-notifications'
param statusNotificationTopicSubscriptionName = 'all-status-notifications'
param webHookNotificationUrl = 'https://webhook.site/a724d362-9cb1-4255-a7b0-6fc514165452'
param sendApprovalTopicName = 'send-credit-approval'
param allCreditApprovalsSubscription = 'all-messages'
param pipelineServicePrincipalId = '7bd78c67-feef-47dd-8ea6-290834596bb1'
