trigger:
  branches:
    include:
     - '*'
pr: none

variables:
  - group: 'order-fulfillment'

stages:
 - stage: Build
   displayName: Build Infrastructure and Code
   jobs:
   - template: templates/build.yaml
     parameters:
       serviceConnectionName: $(SERVICE_CONNECTION_DEV)

 - template: templates/deploy.yaml
   parameters:
     serviceConnectionName: $(SERVICE_CONNECTION_DEV)
     environmentName: dev
     resourceGroupName: $(RESOURCE_GROUP_DEV)

 - template: templates/deploy.yaml
   parameters:
     serviceConnectionName: $(SERVICE_CONNECTION_QA)
     environmentName: qa
     resourceGroupName: $(RESOURCE_GROUP_QA)
